server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bproject?serverTimezone=UTC
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enable: true
jpa:
  hibernate:
    format_sql: true
    show-sql: true